server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: api-serie
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      username: usrseriemongo
      password: pwdseriemongo
      database: seriedevmongo
      port: 27017
      host: localhost
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
