server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: api-catalog
  zipkin:
    base-url: http://localhost:9411
    enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
