server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
  application:
    name: api-movie
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3366/movie-dev-mysql
    username: usr-movie-mysql
    password: pwd-movie-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
